name: syncverse
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  animated_splash_screen: ^1.3.0
  firebase_storage: ^11.2.0
  firebase_auth: ^4.6.0
  cloud_firestore: ^4.9.2
  fluttertoast: ^8.2.1
  firebase_core: ^2.13.1
  firebase_database: ^10.2.2
  firebase_messaging: ^14.6.4
  flutter_local_notifications: ^15.1.1
  animated_notch_bottom_bar: ^1.0.0
  curved_navigation_bar: ^1.0.3
  syncfusion_flutter_charts: ^22.1.38
  flutter_launcher_icons: ^0.13.1
  dot_navigation_bar: ^1.0.2
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  salomon_bottom_bar: ^3.3.2
  glassmorphism: ^3.0.0
  flutter_glassmorpism: ^0.0.3
  glassmorphism_ui: ^0.3.0
  local_auth: ^2.1.6
  url_launcher: ^6.1.12
  flutter_phone_direct_caller: ^2.1.1
  http: ^1.1.0
  flutter_background_service: ^5.0.1
  flutter_background_service_android: ^6.0.1
  permission_handler: ^10.4.3
  pinput: ^3.0.1
  intl_phone_field: ^3.2.0
  wifi_iot: ^0.3.18+1
  connectivity_plus: ^4.0.2
  wifi_info_plugin_plus: ^2.0.2
  web_socket_channel: ^2.4.0
  
  
  

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/run.gif
    - assets/images/wave.jpg
    - assets/Icons/
    - assets/personalIcons/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

